### ISSUE TITLE
[Question] Why, you delete the 1.7.10 generator plugin?

### ISSUE THREAD

**Issue by JLSkyzer** [anatawa12/ForgeGradle-1.2#155]
Why, you delete the 1.7.10 generator plugin for mcreator ?

**Comment by anatawa12** [comment]
Which plugin do you mean? I've removed some plugins in #16.

**Comment by anatawa12** [comment]
@JLSkyzer Can you tell me exact name of the plugin?

**Comment by TheDarkDnKTv** [comment]
Same with cauldron. Since ForgeGradle is broken now, and I'm trying to fix cauldron, I need it.
But it got removed, will try to port some stuff back for now.

**Comment by anatawa12** [comment]
> Same with cauldron. 

For cauldron plugin, it's simple. Because it's (almost) impossible to port cauldron plugin to Gradle 5.0 or later (as described in #14)

> cauldron, mcedu, fmldev, and forgedev plugins are using AbstractTask.execute(), a **internal** api **removed in Gradle 5.0**.

---

The main goal for this fork of ForgeGradle 1.2 is to build Forge mod with modern Gradle to use modern Kotlin in Forge mods.

You still can use official ForgeGradle 1.2. If you don't have to use modern Gradle, use that instead. if you have problem with official ForgeGradle 1.2 (with old Gradle), I may fix & make pull request.

---

Please feel free to make pull request porting those plugins if we can with public apis of Gradle.

**Comment by anatawa12** [comment]
Closing this due to lack of response from original author (Response for Can you tell me exact name of the plugin?)
