### ISSUE TITLE
[Request] Support for Gradle 6

### ISSUE THREAD

**Issue by NeRdTheNed** [anatawa12/ForgeGradle-1.2#9]
I'm sorry for such a large request, but I was wondering if this project would consider supporting Gradle 6.x. One feature of the upcoming Gradle 6.7 release would be very helpfull for me (toolchain support for JVM projects), and Gradle 6.x would offer a boost in performance for most projects using Gradle. I haven't looked into developing Gradle plugins, and I understand if this request would not be considered if this isn't feasible or is just too extensive to do.

**Comment by anatawa12** [comment]
I'm thinking positively to support newest gradle. If possible, please tell me what's the problem with this plug-in with the newest version of gradle?

**Comment by NeRdTheNed** [comment]
The first issue I've found is that it fails to compile on newer versions of Gradle due to not being able to find certain dependencies. [Here is a build scan demonstrating this](https://scans.gradle.com/s/cs6qtbl4qaiia). The project I scanned can be found [here](https://github.com/NeRdTheNed/More-bows). I'd advise you'd test against the example mod for this fork of ForgeGradle-1.2, as my build script has some potentially problematic elements for newer versions of Gradle at the moment (which I intend to fix soon!). I've tested this against the example mod as well, although its dependancies currently need to be updated to build it.

**Comment by NeRdTheNed** [comment]
Update: I've now made a [pull request](https://github.com/anatawa12/ForgeGradle-example/pull/1) with an updated version of the example mod if you want to test with it.

**Comment by anatawa12** [comment]
Thanks for PR for the example project! I'm using the example project now!

**Comment by anatawa12** [comment]
====== MEMOS FOR RESOLVE ======
The reason for the failure:
Failed because 'http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10.pom' is not found. Since Gradle 1.6, pom seem to be required.

Not failed in 1.5.x because pom is not required in Gradle and 'http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-userdev.jar' is exists. ForgeGradle only require userdev.

**Comment by NeRdTheNed** [comment]
Hey @anatawa12, would it be possible to re-open this until 1.2-1.0.3 is released? I understand that you're likely waiting to release it until #15 and #16 are merged.
